"use client";

import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type DocumentItem = {
  id: string;
  job_role: string | null;
  ats_score: number | null;
  created_at: string;
  optimized_cv: string | null;
  cover_letter: string | null;
};

export default function MyDocumentsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (status === "loading") return;

    if (!session?.user?.email) {
      router.push("/login");
      return;
    }

    const fetchDocuments = async () => {
      const { data, error } = await supabase
        .from("generated_documents")
        .select("id, job_role, ats_score, created_at, optimized_cv, cover_letter")
        .eq("user_email", session.user.email)
        .order("created_at", { ascending: false });

      if (!error && data) {
        setDocuments(data);
      }

      setLoading(false);
    };

    fetchDocuments();
  }, [session?.user?.email, status, router]);

  if (loading || status === "loading") {
    return (
      <main className="min-h-screen flex items-center justify-center text-gray-500">
        Loading your documents...
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-slate-50 text-gray-900 px-4 py-10">
      <section className="max-w-5xl mx-auto">
        <div className="bg-black text-white rounded-3xl p-6 shadow-xl">
          <h1 className="text-3xl font-black">📄 My Documents</h1>
          <p className="text-white/70 mt-2">
            View your saved CVs and cover letters generated by Jobify.
          </p>
        </div>

        {documents.length === 0 ? (
          <div className="bg-white border rounded-3xl p-8 mt-6 text-center">
            <h2 className="text-xl font-bold">No documents yet</h2>
            <p className="text-gray-500 mt-2">
              Generate your first CV to see it here.
            </p>

            <button
              onClick={() => router.push("/upload")}
              className="mt-5 bg-black text-white px-6 py-3 rounded-2xl font-bold"
            >
              Generate CV
            </button>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 gap-5 mt-6">
            {documents.map((doc) => (
              <div
                key={doc.id}
                className="bg-white border rounded-3xl p-5 shadow-sm hover:shadow-lg transition"
              >
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <h2 className="font-black text-lg">
                      {doc.job_role || "Generated CV"}
                    </h2>
                    <p className="text-xs text-gray-500 mt-1">
                      {new Date(doc.created_at).toLocaleString()}
                    </p>
                  </div>

                  <span className="bg-green-50 text-green-700 border border-green-100 px-3 py-1 rounded-full text-xs font-bold">
                    {doc.ats_score || 94}% ATS
                  </span>
                </div>

                <p className="text-sm text-gray-600 mt-4 line-clamp-4 whitespace-pre-line">
                  {doc.optimized_cv}
                </p>

                <div className="grid grid-cols-2 gap-3 mt-5">
                  <button
                    onClick={() => navigator.clipboard.writeText(doc.optimized_cv || "")}
                    className="bg-blue-600 text-white py-2 rounded-xl font-bold text-sm"
                  >
                    Copy CV
                  </button>

                  <button
                    onClick={() => navigator.clipboard.writeText(doc.cover_letter || "")}
                    className="bg-purple-600 text-white py-2 rounded-xl font-bold text-sm"
                  >
                    Copy Letter
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>
    </main>
  );
}
